### ISSUE TITLE
Crash when searching under Internet tab with Spotify

### ISSUE THREAD

**Issue by MelissaManley97** [Team-NullPointer/Clementine#12] opened 2017-03-03 04:01 UTC
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Latest version of Windows 10, OSX and Ubuntu.
- Clementine version: Latest release and latest build with last commit being: 27bf50d

### Expected behavior / actual behavior

Expected behavior:
It is expected that when the user wishes to "Search on Spotify" under the Internet
tab, they would be able to enter a string of their choosing, press "enter," and
a search for that string would return appropriate results.

Actual behavior:
When a user types a string in "Search on Spotify" under the Internet tab, one of
two results occur:
1. If the user enters a relatively long string, such as "Hello world. This is a particularly long string," then Clementine will crash before the user can press "enter" for their search.
2. If the user enters a relatively short string, such as "Hello," and then the user presses "enter" to commence the search, Clementine will then crash after the user presses the "enter" key.

This error message appears in Application Output of Qt after Clementine crashes:
![image](https://images.discordapp.net/.eJwFwVEOwiAMANC7cAA6K7Sy2xBG2OJGCe3ih_Huvvd19zzd6nazoSvAdmiRuXk1mblV30TaWfM41Be5IJvlsl-1mwIyxZSQeQnESBQJ8MVLpMiBMKUnPyjA3d9dPt2P3tzvDwv4Iv8.FaaZnVeRFeOtpCmyJxTYQiMA8gg)

It would be useful for Spotify members who use Clementine to be able to search under the Internet tab without the program crashing. Appropriate steps to reproduce the bug with screenshots are shown below.

### Steps to reproduce the problem (only for bugs)
1.       Configure a Spotify account in Clementine (if you have already done this, skip to step 2)
a.       Open Clementine
b.       Click the “Internet” tab
![image](https://cloud.githubusercontent.com/assets/25350560/23537798/8904c208-ff9c-11e6-8018-2d7e439eb9d8.png)

c. Right click “Spotify” under this tab and then left click “Configure Spotify”
![image](https://cloud.githubusercontent.com/assets/25350560/23537612/3b6b0cc4-ff9b-11e6-82ca-8562f6dc8322.png)

d. Sign into your Spotify account. This is will only work if you have a premium account (Clementine can only support premium Spotify accounts). Then close out of preferences.

2.  Make sure you are under the “Internet” tab in Clementine. Now left click on “Spotify”
![image](https://cloud.githubusercontent.com/assets/25350560/23537653/943cc022-ff9b-11e6-955e-de81fdd0b942.png)

3. A  “Search on Spotify” box should now appear at the top of the page. Type a song/artist/album in this search box and press “enter”.
![image](https://cloud.githubusercontent.com/assets/25350560/23537656/9a769454-ff9b-11e6-98d7-e2d49ac2e01f.png)

4. Clementine will either exit/crash while you are typing in the search box or after you press enter.

**Comment by ghost** [comment] 2017-03-04 05:46
From what I can gather, the issue is in these lines. [Here](https://github.com/Team-NullPointer/Clementine/blob/master/src/internet/spotify/spotifyservice.cpp#L768-L772)

It seems like search_ has a null pointer and because of that when you try to run search_->appendRow(child) it crashes because search_ points to nothing.

**Comment by MelissaManley97** [comment] 2017-03-08 20:59
The issue definitely seems to be coming from those lines.
search_ is initialized as nullptr at the top of spotifyserver.cpp, and it appears it was never given a value other than that when the search occurs
Beginning on line 405 of the file you posted (spotifyservice.cpp), there is a check for if search is null. If search is null, there is a decent amount of code that initializes the search pointer.
If all of this code is put into a function, say "InitSearch()", then that function can be called at that time and in the function where the code is breaking. For example, where the code is currently breaking, insert:

// Must initialize search pointer if it is nullptr
  if (!search_) {
      InitSearch();
  }
  // Fill results list
  for (const Song& song : songs) {
    QStandardItem* child = CreateSongItem(song);
    search_->appendRow(child);
  }

The InitSearch() function was created using what the file already had to initialize search starting on line 405. It seemed like a good idea to just have a function for it instead of copy/pasting the code twice.

This fix made searching work for any size string. Changed lines of affected files are here:
[spotifyserverHeaderDiff.docx](https://github.com/Team-NullPointer/Clementine/files/828941/spotifyserverHeaderDiff.docx)
[spotifyserverCPP Diff.docx](https://github.com/Team-NullPointer/Clementine/files/828945/spotifyserverCPP.Diff.docx)

**Comment by ghost** [comment] 2017-03-09 01:04
Fixed with 5ea6b95e5ff2261fa55aff667ec0c86317356f97.

**Closed as completed** 2017-03-14 01:32 UTC
Labels: bug, Fixed
